# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Cameron Lowry
# title:
email: cameron.lowry@cuanschutz.edu
# website:

# Dark Mode (true/false/never)
darkmode: false

# Additional icon links
additional_links:
- title: CV
  icon: fas fa-file-alt
  url: https://cameronlowry.com/Cameron_Lowry_CV.pdf

- title: GitHub
  icon: fab fa-github
  url: https://github.com/lowrycam

- title: LinkedIn
  icon: fab fa-linkedin
  url: https://linkedin.com/in/lowrycam

- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=9w7i7oAAAAAJ

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  PhD Student<br>
  <a href = "https://pharmacy.cuanschutz.edu/degreesandprograms/phd-programs/pharmaceutical-sciences">Pharmaceutical Sciences Program</a><br>
  University of Colorado Anschutz Medical Campus<br>
  Research Assistant in the <a href = "https://thekrishnanlab.org">Krishnan Lab</a>

# Footer
# footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
